<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="McpToolkit.Client" Version="0.1.3" />
      <PackageReference Include="Microsoft.Extensions.AI" Version="9.6.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.7" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.7" />
      <PackageReference Include="ModelContextProtocol" Version="0.3.0-preview.1" />
    </ItemGroup>
     <ItemGroup>
      <ProjectReference Include="..\BOT.Application\BOT.Application.csproj" />
      <ProjectReference Include="..\BOT.Domain\BOT.Domain.csproj" />
    </ItemGroup>

</Project>
